{
  parser: 'babel-eslint',
  extends: 'airbnb',
  env: { es6: true, browser: true, node: true },
  settings: { 'import/resolver': { webpack: { config: 'webpack/base.config.js' } } },
  rules:
    {
      'react/jsx-filename-extension': [1, { extensions: ['.js', '.jsx', '.ts', '.tsx'] }],
      'import/no-extraneous-dependencies': ['error', { devDependencies: true }],
      'react/destructuring-assignment': ['off'],
      'import/prefer-default-export': ['off'],
    },
}
