language: node_js

node_js:
 - "8"

before_install:
  - nvm install 8.0.0
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH="$HOME/.yarn/bin:$PATH"
  - node -v
  - yarn -v

install:
  - yarn

cache:
  yarn: true
  directories:
    - node_modules'

script:
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Generate your github token and pass secretly as a variable
  keep-history: true
  on:
    branch: master